### ISSUE TITLE
Get model of a SAT instance

### ISSUE THREAD

**Issue by arey0pushpa** [lonsing/depqbf#15]
Thanks for the great tool.
How i can get a  satisfying assignment if i use QDIMACS file as an input.

**Comment by lonsing** [comment]
Hi,

you can get a satisfying assignment by using the '--qdo' command line option, or, when you are using the solver API, by function 'qdpll_get_value(...)'.

See also the related posting: https://github.com/lonsing/depqbf/issues/12

Best regards,
Florian

**Comment by arey0pushpa** [comment]
Thank you so much. Helpful.
