### ISSUE TITLE
doc request: difference between --qbce-preprocessing and bloqqer

### ISSUE THREAD

**Issue by jwaldmann** [lonsing/depqbf#7]
Hi. 

What is the difference between calling `bloqqer` as a preprocessor, and using `--qbce-preprocessing`?
(are there `--qbce-*` parameter settings that would achieve what `bloqqer` does?)

In our application, we actually want `--qdo` which is not available when using `bloqqer` (since there is no `unbloqqer` back-transformation)?

**Comment by lonsing** [comment]
Hi,

Both bloqqer and DepQBF apply certain default limits when running QBCE to stop QBCE after a certain amount of work has been spent. Hence in general, QBCE is not applied until completion. However, you may increase the limits, e.g. in DepQBF by parameters '--qbce-witness-max-occs=<val>' and '--qbce-max-clause-size=<val>'. The higher the limits, the more time will be spent in QBCE. QBCE should until completion if the limits are very high, like 10^6.

Bloqqer has similar parameters to control QBCE. If you would like Bloqqer and DepQBF to result in the same behavior then you must disable all techniques other than QBCE in Bloqqer (DepQBF has only QBCE).

Bloqqer also allows to produce a partial assignment like DepQBF does with option '--qdo'. However, I think that DepQBF has to be linked to Bloqqer for that purpose, if I am not mistaken. See option '-m' in Bloqqer.

**Comment by jwaldmann** [comment]
> Bloqqer also allows to produce a partial assignment ... 

Ah - interesting. Since that was not obvious from the docs, here's the steps to actually get this behaviour:

* check out bloqqer and depqbf
* build depqbf (in-place)
* in bloqqer, change line in `configure` to `DEPQBF=../depqbf`, then `./configure -s && make`

then `bloqqer -m` prints the processed cnf (this can be switched off by `--output=0`), calls the solver,
and prints the partial assignment (ending with `2`, probably indicating that it is partial)

example: input
```
p cnf 3 3
e 1 0 a 2 0 e 3 0 1 -3 2 0 -2 3 0 -2 -1 0
```
call
```
./bloqqer test.qbf -m --output=0 --verbose=1
```
